use_frameworks!

platform :ios, '8.0'

target 'EaseAlertController_Example' do
  pod 'EaseAlertController', :path => '../'

  target 'EaseAlertController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
